name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Setup env
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      - name: Run codegen
        uses: borales/actions-yarn@v4
        with:
          cmd: codegen:no-verbose
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/ package.json yarn.lock"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_AFTER: |
            whoami
            cd "${{ secrets.REMOTE_TARGET }}"
            pwd
            echo """${{ secrets.BACKEND_ENV }}""" > .env
            screen -S sapphire -X quit || true
            yarn install --production --frozen-lockfile --ignore-scripts
            screen -S sapphire -d -m 'node server.js'
          SCRIPT_AFTER_REQUIRED: true